# Required Settings
region: 'My City'
password: '__make_your_own_management_password__'
cookie_secret: '__this_can_be_anything_it_is_just_for_the_server__'
# Optional settings
google_analytics_id: '__optional_just_remove_this_line_if_not_needed__'
max_file_size: 104857600
read_only: false
admin_emails: ['admin1@example.com', 'admin2@example.com']
from_email: 'noreply@example.com'
app_root: 'https://docs.example.com'
smtp_host: 'smtp.example.com'
smtp_port: 587
smtp_username: 'smtp_user@example.com'
smtp_password: 'smtp_password'
